sonar.verbose=true
sonar.organization=vivekpr5-key
sonar.projectKey=vivekpr5-key_twittertrend
sonar.projectName=twittertrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
